"""Roadmap lookup.

`get_roadmap(career_id)` is the single seam the API calls: it returns the curated
static roadmap from data/roadmaps.json, in this shape —
  { "sections": [ { "id","label","nodes":[
      {"id","label","level","type","description","resources":[{"title","url"}]} ] } ] }

There is no LLM path. Roadmaps used to be generated by OpenAI whenever a key and
some personalization context were present, with the static file as the fallback;
that was removed deliberately. Roadmaps are now hand-curated and deterministic —
which is also what lets the UI number the nodes in a stage 1..n as a learning
sequence (DEV-81), a claim generated content couldn't honestly support.

The one thing still layered on top is deterministic, not generative: job-ad-derived
market stages, appended by inject_requirements() below.
"""
import re

from common.data import load_roadmaps


def get_roadmap(career_id: str) -> dict | None:
    """The curated roadmap for a career, or None if there isn't one."""
    return load_roadmaps().get(career_id)


# Symbols that distinguish otherwise-identical skill names must survive slugging:
# stripping them made "C#" and "C++" both collapse to "c" (duplicate node ids).
_SLUG_SYMBOLS = {"#": " sharp ", "+": " plus "}


def _slug(text: str) -> str:
    for sym, word in _SLUG_SYMBOLS.items():
        text = text.replace(sym, word)
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "skill"


def _unique_id(base: str, seen: set[str]) -> str:
    """Guarantee a DOM/React-key-safe unique id, even if two distinct skills still slug
    to the same base (belt-and-suspenders beyond _SLUG_SYMBOLS). Deterministic: nodes
    are built in a stable frequency-descending order, so the -2/-3 suffixes are stable."""
    candidate, n = base, 2
    while candidate in seen:
        candidate, n = f"{base}-{n}", n + 1
    seen.add(candidate)
    return candidate


def _requirement_node(item: dict, classification: str, seen: set[str]) -> dict:
    """One job-ad-derived skill as a roadmap node carrying a `demand` badge payload.
    `seen` tracks ids already emitted so distinct skills never share a node id."""
    skill, pct, count, total = item["skill"], item["pct"], item["count"], item["total"]
    if classification == "required":
        node_type = "required"
        description = f"Required in {pct}% of job ads ({count} of {total} analyzed)."
    else:
        node_type = "good-to-know"
        description = f"Listed as an advantage in {pct}% of job ads ({count} of {total} analyzed)."
    return {
        "id": _unique_id(f"market-{_slug(skill)}", seen),
        "label": skill,
        "level": "intermediate",
        "type": node_type,
        "description": description,
        "resources": [],
        "demand": {"classification": classification, "count": count, "total": total, "pct": pct},
    }


def inject_requirements(roadmap: dict, requirements: dict | None) -> dict:
    """Append job-ad-derived skill nodes as their own pipeline stages: a separate
    'In Demand Now' (required) column and a 'Gives an Advantage' (advantage) column.

    Returns a NEW dict with a copied `sections` list — never mutates the input, because
    the static roadmap comes from load_roadmaps()'s @lru_cache and is shared across
    requests. Returns the roadmap unchanged when there are no requirements to show.
    """
    required = (requirements or {}).get("required", [])
    advantage = (requirements or {}).get("advantage", [])
    if not required and not advantage:
        return roadmap

    # One id namespace across both columns so no two market nodes ever collide.
    seen: set[str] = set()
    extra: list[dict] = []
    if required:
        extra.append({
            "id": "in-demand",
            "label": "In Demand Now",
            "source": "job_ads",
            "nodes": [_requirement_node(i, "required", seen) for i in required],
        })
    if advantage:
        extra.append({
            "id": "advantage",
            "label": "Gives an Advantage",
            "source": "job_ads",
            "nodes": [_requirement_node(i, "advantage", seen) for i in advantage],
        })
    return {**roadmap, "sections": [*roadmap.get("sections", []), *extra]}
